
mapfile:
  conda env: esgf-prep
  commands: [
    'esgmapfile make -i /datalocal/config/esgcet/ --project {project} {dataset_path} --outdir {mapfile_path}'
  ]
  mapfile_dir : mapfiles
  mapfile_subdir: '{project}/{activity_id}/{institution_id}/{source_id}/{experiment_id}/{member_id}'
  clobber: False

publish:
  conda env: esgf-pub524
  commands: [
    'esgpublish --map {mapfile} -cfg /home/acrnpub/.esg/esg.yaml --no-auth',
  ]

DRS:
  cmip6:
    dataset : '{project}.{activity_id}.{institution_id}.{source_id}.{experiment_id}.{member_id}.{table_id}.{variable_id}.{grid_label}.{version}'
    path :    '{project}/{activity_id}/{institution_id}/{source_id}/{experiment_id}/{member_id}/{table_id}/{variable_id}/{grid_label}/{version}'
#    file :    '{variable_id}_{table_id}_{source_id}_{experiment_id}_{member_id}_{grid_label}_{time_subset}.nc'

