
project: cmip6

datasets:
  CMIP6/DCPP/CCCma/CanESM5/dcppB-forecast/s2022-r1i1p2f1/
  # CMIP6/DCPP/CCCma/CanESM5/dcppB-forecast/s2022-r1i1p2f1/Amon/tas/gn/v20190429
#  CMIP6/DCPP/CCCma/CanESM5/dcppB-forecast/s2022-r1i1p2f1/Amon/uas/gn/v20190429

keep: 
  experiment_id : dcppB-forecast
  variable_id : ['tas', 'tasmax']
  table_id : [Amon, SImon]

paths:
  /space/hall5/sitestore/eccc/crd/ccrn/model_output/CMIP6/final/


validation_info : input/validation_variables.json

DRS:
  cmip6:
    dataset : '{project}.{activity_id}.{institution_id}.{source_id}.{experiment_id}.{member_id}.{table_id}.{variable_id}.{grid_label}.{version}'
    path :    '{project}/{activity_id}/{institution_id}/{source_id}/{experiment_id}/{member_id}/{table_id}/{variable_id}/{grid_label}/{version}'
    file :    '{variable_id}_{table_id}_{source_id}_{experiment_id}_{member_id}_{grid_label}_{time_subset}.nc'


