
project: cmip6

datasets:
  CMIP6/DCPP/CCCma/CanESM5/dcppB-forecast/s2022-r1i1p2f1/
  # CMIP6/DCPP/CCCma/CanESM5/dcppB-forecast/s2022-r1i1p2f1/Amon/tas/gn/v20190429
  # CMIP6/DCPP/CCCma/CanESM5/dcppB-forecast/s2022-r1i1p2f1/Amon/uas/gn/v20190429


keep: 
  variable_id : [tas, tasmax, tasmin]
#  experiment_id : dcppB-forecast
#  table_id : [Amon, SImon]

paths:
  /esgH/data/AR6/
  /space/hall5/sitestore/eccc/crd/ccrn/model_output/CMIP6/final/


