
mapfile:
  venv: /home/scrd106/rja001/venv/pub_test
  commands: [
    'esgmapfile make --project {project} --outdir {mapfile_path} --directory {dataset_path}'
  ]
  mapfile_dir : mapfiles
  mapfile_subdir: 
    #cmip7: '{drs_specs}/{mip_era}/{activity_id}/{institution_id}/{source_id}/{experiment_id}/{variant_label}'
    cmip7: ''
  clobber: False

publish:
  venv: /home/scrd106/rja001/venv/pub_test
  commands: [
    # 'esgpublish --map mapfile_list --config esg_east.yaml',
    # 'esgpublish --map {mapfile} --config $REPO_PATH/esg_ng/esgcet_files/esg_east.yaml'
    'esgpublish --map {mapfile} --config esg_east.yaml'
  ]

search_esgf: 
  index_node: esgf-node.llnl.gov
  verbose: False
  show_browser_url: False

DRS:
  cmip7:
    # for guidance see https://wcrp-cmip.github.io/cmip7-guidance/docs/CMIP7/Global_Attributes/
    dataset : '{drs_specs}.{mip_era}.{activity_id}.{institution_id}.{source_id}.{experiment_id}.{variant_label}.{region}.{frequency}.{variable_id}.{branding_suffix}.{grid_label}.{version}'
    path :    '{drs_specs}/{mip_era}/{activity_id}/{institution_id}/{source_id}/{experiment_id}/{variant_label}/{region}/{frequency}/{variable_id}/{branding_suffix}/{grid_label}/{version}'
